use_frameworks!

platform :ios, '11.0'

target 'TinyKit_Example' do
  
  pod 'TinyKit',          :path => '../'
  pod 'MLeaksFinder',     :configurations => ['Debug']
  
  
  
  target 'TinyKit_Tests' do
    inherit! :search_paths

    
  end
end
